---
title: "data_clean"
author: "Millie Chapman"
date: "12/21/2019"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(splitstackshape)
library(stringr)
rm(list = ls())
```

```{r}
##variables
#vars<-c("NAME_EN", "b1", "BIOME", "ECONOMY", "POP_EST", "INCOME_GRP", "ISO_A3")
vars<-c("NAME_EN", "min", "BIOME_NAME", "ECONOMY", "POP_EST", "INCOME_GRP", "ISO_A3")
biomes<-read_csv("../data/Biome_names.csv")

class<- read.csv("../data/gdp_classification.csv") %>%
  mutate(ISO_A3 = Country.Code) %>%
  select(ISO_A3, IncomeGroup) %>%
  mutate(ECONOMY = IncomeGroup) 
```

```{r}
##load crop
crop_hist<- read.csv("../data/data_new/crop_hist_25.csv") %>%
  select(vars) %>% mutate(b1 = min) %>%
  left_join(class, by = "ISO_A3") %>%
  drop_na("ISO_A3")
  

# filter frequency hist
crop_hist$b1<- str_sub(crop_hist$b1, 2, -2)
crop_hist$b1<- as.character(crop_hist$b1)
crop_hist <- cSplit(crop_hist, "b1", sep = ",", direction = "long")
crop_hist <- cSplit(crop_hist, "b1", sep = "=", direction = "wide")

crop_histL<- crop_hist %>%
  filter(b1_1<10) 


sum(crop_histL$b1_2)*.09/10^6/(sum(crop_hist$b1_2)*.09/10^6)
```

```{r}
##load crop
crop_area_all <- read_csv("../data/crop_area_all.csv") 
crop_biomass_all <- read_csv("../data/crop_biomass_all.csv")

crop_area_25 <- read_csv("../data/crop_area_25.csv") %>%
  mutate(area = min) %>% select(-min) %>%
  group_by(BIOME_NAME, NAME_EN, ISO_A3, INCOME_GRP) %>% 
  summarise(area_crop = sum(area))

crop_biomass_25 <- read_csv("../data/crop_biomass_25.csv") %>% 
  mutate(biomass = min) %>% select(-min) %>%
  group_by(BIOME_NAME, NAME_EN, ISO_A3, INCOME_GRP) %>% 
  summarise(biomass_crop = sum(biomass))

crop <- crop_area_25 %>% left_join(crop_biomass_25) %>%
  mutate(biomass_crop = (biomass_crop - area_crop)/2)

sum(crop$area_crop)/10^9
sum(crop$biomass_crop)/10^9

add_area <- sum(crop_area_all$min)/10^9 - sum(crop$area_crop)/10^9

add_biomass <- (sum(crop_biomass_all$min)/10^9 - sum(crop_area_all$min)/10^9)/2 - sum(crop$biomass_crop)/10^9

add_biomass/add_area
```
```{r}
##load pastture
pasture_area_25 <- read_csv("../data/pasture_area_25.csv") %>%
  mutate(area = min) %>% select(-min) %>%
  group_by(BIOME_NAME, NAME_EN, ISO_A3, INCOME_GRP) %>% 
  summarise(area_pasture = sum(area))

pasture_biomass_25 <- read_csv("../data/pasture_biomass_25.csv") %>%
  mutate(biomass = min) %>% select(-min) %>%
  group_by(BIOME_NAME, NAME_EN, ISO_A3, INCOME_GRP) %>% 
  summarise(biomass_pasture = sum(biomass))

pasture <- pasture_area_25 %>% left_join(pasture_biomass_25) %>%
  mutate(biomass_pasture = (biomass_pasture - area_pasture)/2) %>%
  drop_na(biomass_pasture)


sum(pasture$biomass_pasture)/10^9
sum(pasture$area_pasture)/10^9
```

```{r}
data <- crop %>% left_join(pasture)
```

```{r}
######## country summary #############
summary_country <- data %>%
  group_by(NAME_EN, ISO_A3, INCOME_GRP) %>%
  summarise(biomass_crop = sum(biomass_crop, na.rm = TRUE),
            biomass_pasture = sum(biomass_pasture, na.rm = TRUE),
            area_crop = sum(area_crop, na.rm = TRUE),
            area_pasture = sum(area_pasture, na.rm = TRUE)) %>%
  mutate(total_area = area_crop + area_pasture,
         total_biomass = biomass_pasture + biomass_crop,
         density_crop = biomass_crop/area_crop,
         density_pasture = biomass_pasture/area_pasture)
```


```{r}
###### Biome Summary ############
summary_biome <- data %>%
  group_by(BIOME_NAME) %>%
  summarise(biomass_crop = sum(biomass_crop, na.rm = TRUE),
            biomass_pasture = sum(biomass_pasture, na.rm = TRUE),
            area_crop = sum(area_crop, na.rm = TRUE),
            area_pasture = sum(area_pasture, na.rm = TRUE)) %>%
  mutate(total_area = area_crop + area_pasture,
         total_biomass = biomass_pasture + biomass_crop,
         density_crop = biomass_crop/area_crop,
         density_pasture = biomass_pasture/area_pasture)
```

```{r}
######## Economy Summary ############
summary_economy <- data %>%
  group_by(INCOME_GRP) %>%
  summarise(biomass_crop = sum(biomass_crop, na.rm = TRUE),
            biomass_pasture = sum(biomass_pasture, na.rm = TRUE),
            area_crop = sum(area_crop, na.rm = TRUE),
            area_pasture = sum(area_pasture, na.rm = TRUE)) %>%
  mutate(total_area = area_crop + area_pasture,
         total_biomass = biomass_pasture + biomass_crop,
         density_crop = biomass_crop/area_crop,
         density_pasture = biomass_pasture/area_pasture)
```

```{r}
########Summary all ###############
summary_all <- data %>%
  mutate(total_area = area_crop + area_pasture,
         total_biomass = biomass_pasture + biomass_crop,
         density_crop = biomass_crop/area_crop,
         density_pasture = biomass_pasture/area_pasture)
```

```{r}
write.csv(summary_biome, "../output/summary_biome.csv")
write.csv(summary_country, "../output/summary_country.csv")
write.csv(summary_economy, "../output/summary_economy.csv")
write.csv(summary_all, "../output/summary_all.csv")
```

```{r}
##table 1
summary_biome <- data %>%
  group_by(BIOME_NAME) %>%
  summarise(biomass_crop = sum(biomass_crop, na.rm = TRUE)/10^6,
            biomass_pasture = sum(biomass_pasture, na.rm = TRUE)/10^6,
            area_crop = sum(area_crop, na.rm = TRUE)/10^6,
            area_pasture = sum(area_pasture, na.rm = TRUE)/10^6) %>%
  mutate(total_area = area_crop + area_pasture,
         total_biomass = biomass_pasture + biomass_crop,
         density_crop = biomass_crop/area_crop,
         density_pasture = biomass_pasture/area_pasture)
write.csv(summary_biome, "../output/summary_biome_table.csv")

```

supporting table
```{r}
summary_supp <- data %>%
  mutate(area_crop = area_crop/10^6,
         area_pasture = area_pasture/10^6,
         biomass_crop = biomass_crop/10^6,
         biomass_pasture = biomass_pasture/10^6)

summary_supp <- summary_supp %>%
  mutate(total_area = area_crop + area_pasture,
         total_biomass = biomass_pasture + biomass_crop,
         density_pasture = biomass_pasture/area_pasture,
         density_crop = biomass_crop/area_crop)

write.csv(summary_supp, "../output/summary_supp_table.csv")


```
```

