---
title: "potential"
author: "Millie Chapman"
date: "12/21/2019"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(splitstackshape)
library(stringr)
rm(list = ls())
```

```{r}
##variables
#vars<-c("NAME_EN", "b1", "BIOME", "ECONOMY", "POP_EST", "INCOME_GRP", "ISO_A3")
vars<-c("NAME_EN", "min", "BIOME_NAME", "ECONOMY", "POP_EST", "INCOME_GRP", "ISO_A3")
biomes<-read_csv("../data/Biome_names.csv")



class<- read.csv("../data/gdp_classification.csv") %>%
  mutate(ISO_A3 = Country.Code) %>%
  select(ISO_A3, IncomeGroup) %>%
  mutate(ECONOMY = IncomeGroup)

```

```{r}
##load crop
vars<-c("NAME_EN", "min", "BIOME_NAME", "ECONOMY", "POP_EST", "INCOME_GRP", "ISO_A3")

crop_hist<- read_csv("../data/crop_hist_25.csv") %>%
  select(vars) %>% mutate(b1 = min) %>%
  left_join(class, by = "ISO_A3") %>%
  drop_na("ISO_A3")
  

# filter frequency hist
crop_hist$b1<- str_sub(crop_hist$b1, 2, -2)
crop_hist$b1<- as.character(crop_hist$b1)
crop_hist <- cSplit(crop_hist, "b1", sep = ",", direction = "long")
crop_hist <- cSplit(crop_hist, "b1", sep = "=", direction = "wide")
```

```{r}
##load pasture
pasture_hist<- read.csv("../data/pasture_hist_25.csv") %>%
 select(vars)  %>% mutate(b1 = min) %>%
 left_join(class) %>%
 drop_na("ISO_A3")


#format frequency hist
pasture_hist$b1<- str_sub(pasture_hist$b1, 2, -2)
pasture_hist$b1<- as.character(pasture_hist$b1)
pasture_hist <- cSplit(pasture_hist, "b1", sep = ",", direction = "long")
pasture_hist <- cSplit(pasture_hist, "b1", sep = "=", direction = "wide")
```

```{r}
crop_all <- crop_hist %>%
  group_by(BIOME_NAME, ISO_A3, b1_1) %>% drop_na(BIOME_NAME) %>% #drop_na(ISO_A3) %>%
  summarise(b1_2 = sum(b1_2)) %>%
  mutate(b1_1 = b1_1-1,
         b1_2 = as.numeric(b1_2),
         biomass = b1_1*b1_2*.09,
         BIOME = as.numeric(BIOME_NAME))

pasture_all <- pasture_hist %>%
  group_by(BIOME_NAME,ISO_A3, b1_1) %>% 
  #drop_na(BIOME_NAME) %>% drop_na(ISO_A3) %>%
  summarise(b1_2 = sum(b1_2)) %>%
  mutate(b1_1 = b1_1-1,
         b1_2 = as.numeric(b1_2),
         biomass = b1_1*b1_2*.09,
         BIOME = as.numeric(BIOME_NAME))

listc<-split(crop_all, paste(crop_all$ISO_A3,crop_all$BIOME))

listp<-split(pasture_all,paste(pasture_all$ISO_A3,pasture_all$BIOME))
```

```{r}
quantiles = function(x,probs) {
  z<- with(x, quantile(rep.int(b1_1, b1_2), probs))
  return(data.frame(id = probs, values = z))
} 
```

```{r}
for (i in 1:length(listc)) {
  listc[[i]]$b1_1<-as.numeric(listc[[i]]$b1_1)
  z <- subset(listc[[i]], b1_1 > 10 )
  a<-quantiles(z, probs = c(0.1,0.2,0.5))
  listc[[i]]$p50<-a$values[3]
  listc[[i]]$d50<-ifelse(listc[[i]]$b1_1<10,listc[[i]]$p50-listc[[i]]$b1_1,0)
  listc[[i]]$a50<-ifelse(listc[[i]]$d50>0,listc[[i]]$b1_2*0.09,0)
  listc[[i]]$b50<-listc[[i]]$d50*listc[[i]]$a50
}
```

```{r}
crops_potential <- do.call("rbind", listc) 

crops_potential <- crops_potential %>%
  group_by(BIOME, ISO_A3) %>%
  summarise(carbon_potential = sum(b50)/2,
            potential_value = mean(p50)) %>%
  mutate(CP = "crop")

sum(na.omit(crops_potential$carbon_potential))/10^9
```

```{r}
for (i in 1:length(listp)) {
  listp[[i]]$b1_1<-as.numeric(listp[[i]]$b1_1)
  z <- subset(listp[[i]], b1_1 > 10 )
  a<-quantiles(z, probs = c(0.1,0.2,0.5))
  listp[[i]]$p50<-a$values[3]
  listp[[i]]$d50<-ifelse(listp[[i]]$b1_1<10,listp[[i]]$p50-listp[[i]]$b1_1,0)
  listp[[i]]$a50<-ifelse(listp[[i]]$d50>0,listp[[i]]$b1_2*0.09,0)
  listp[[i]]$b50<-listp[[i]]$d50*listp[[i]]$a50
}
```

```{r}
pastures_potential <- do.call("rbind", listp) 

pastures_potential <- pastures_potential %>%
  group_by(BIOME, ISO_A3) %>%
  summarise(carbon_potential = sum(b50)/2,
            potential_value = mean(p50)) %>%
  mutate(CP = "pasture")
sum(na.omit(pastures_potential$carbon_potential))/10^9 + sum(na.omit(crops_potential$carbon_potential))/10^9


potential<- rbind(pastures_potential, crops_potential)
```

```{r}
write.csv(potential, "../output/potential.csv")
```

```{r}
poten<-read_csv("../output/potential.csv")%>%
  group_by(CP) %>% 
  summarize(carbon = sum(carbon_potential, na.rm = TRUE)/10^6)

sum(poten$carbon)

```


